### ISSUE TITLE
Problem with TokenInfo object on @advanced-rest-client/arc-types/src/oauth2/OAuth2 resources

### ISSUE THREAD

**Issue by Debaerdm** [advanced-rest-client/electron-oauth2#5]
Hello,

I'm currently trying you'r OAuth Electron implementation on my project, and i have seen a error during my code compilation, like this :

![image](https://user-images.githubusercontent.com/11472512/99983336-04051980-2dac-11eb-95c3-e49b585650f8.png)

And i'm going to look you'r implementation and i see this :
![image](https://user-images.githubusercontent.com/11472512/99983414-1ed78e00-2dac-11eb-8afc-d5c6369614a6.png)
![image](https://user-images.githubusercontent.com/11472512/99983513-3a429900-2dac-11eb-9672-0f9077aa106a.png)

The folder "oAuth2" is not included on arc-types/src folder, do you know this issue ? 

Thanks !

**Comment by jarrodek** [comment]
Hi,
Sorry for the late response. GitHub stopped sending me any notifications about issues. I just read this by accident. 

I haven't updated this repository in a while. The types has changes and the oath configuration has been merged with the `authorization` folder. The right path (already corrected some time ago) is `import { TokenInfo, TokenRemoveOptions } from '@advanced-rest-client/arc-types/src/authorization/Authorization';`
